import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { useSelector } from "react-redux";

import Head from "next/head";
import { useRouter } from "next/router";
import { initApps } from "../actions";

import styles from "../styles/Home.module.css";

export default function Home() {
  const navigate = useRouter();
  const dispatch = useDispatch();
  const AppName = useSelector((state) => state.title);

  useEffect(() => {
    dispatch(initApps());
  }, [dispatch]);

  const onBeginClaim = () => navigate.push("/wizards/form");
  return (
    <div className={styles.container}>
      <Head>
        <title>{AppName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{AppName}</h1>

        <div
          style={{
            margin: "1rem 4rem",
            textAlign: "center",
          }}
        >
          <p>
            Click &ldquo;Claim&ldquo; button below to begin claim your
            compensation.
          </p>
          <button onClick={onBeginClaim}>Claim</button>
        </div>
      </main>
    </div>
  );
}
